<?php
function greetings_menu() {
    $items = array();
    $items['hello'] = array(
        'title' => 'Hallo',
        'page callback' => 'hello_buddy',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['farewell'] = array(
        'title' => 'Farewell',
        'page callback' => 'farewell_buddy',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function hello_buddy() {
    return "<p>Hello buddy, how are your dogs?</p>";
}

function farewell_buddy() {
    return "<p>By the grace of the gods, be well.</p>";
}

function greetings_user_login(&$edit, $account) {
    if(in_array('reviewer', $account->roles)) {
        $_GET['destination'] = 'node/add/book-review';
    }
}

function greetings_user_logout() {
    $_GET['destination'] = 'farewell';
}
